name: Git Clone, Unzip, Install, and Run

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'
  schedule:
    - cron: '0 */5 * * *'  # Jalankan setiap 5 jam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the target repository
    - name: Clone Runbot repository
      run: |
        git clone https://github.com/Yudzxml/Runbot.git

    # Step 2: Navigate into the Runbot directory
    - name: Change directory to Runbot
      run: cd Runbot

    # Step 3: Unzip x7botz.zip file inside the Runbot folder
    - name: Unzip x7botz.zip
      run: |
        sudo apt-get install unzip  # Install unzip tool if not already installed
        unzip Runbot/x7botz.zip -d ./Runbot # Unzip x7botz.zip in the Runbot directory

    # Step 4: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd Runbot
        npm install

    # Step 5: Install pm2 globally
    - name: Install pm2
      run: |
        npm install -g pm2

    # Step 6: Start the application with pm2
    - name: Start the application with pm2
      run: |
        cd Runbot
        pm2 start npm --name "runbot" -- start
